<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { Download, Mail } from '@lucide/vue'
import HrLayout from '@/layouts/HrLayout.vue'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription } from '@/components/ui/alert'
import PrivacyBanner from '@/components/layout/PrivacyBanner.vue'
import DropdownSelect from '@/components/common/DropdownSelect.vue'
import KpiCard from '@/components/kpi/KpiCard.vue'
import SentimentBar from '@/components/kpi/SentimentBar.vue'
import TrendLineChart from '@/components/charts/TrendLineChart.vue'
import HeatmapGrid from '@/components/charts/HeatmapGrid.vue'
import WordCloud from '@/components/charts/WordCloud.vue'
import DepartmentSummaryTable from '@/components/charts/DepartmentSummaryTable.vue'
import DashboardAlerts from '@/components/dashboard/DashboardAlerts.vue'
import AiInsightPanel from '@/components/dashboard/AiInsightPanel.vue'
import UrgentIssuesList from '@/components/dashboard/UrgentIssuesList.vue'
import { useAsyncData } from '@/composables/useAsyncData'
import * as dashboardApi from '@/api/dashboard'
import * as periodsApi from '@/api/periods'
import { ApiError } from '@/api/client'

const { t, locale } = useI18n()
const router = useRouter()

const selectedPeriod = ref('')
const selectedDepartment = ref('all')

const { data: periods } = useAsyncData(() => periodsApi.list())

const periodOptions = computed(() =>
  (periods.value ?? []).map((p) => ({
    value: p.id,
    label: `${p.year}-${String(p.month).padStart(2, '0')}`,
  })),
)

watch(periods, (list) => {
  if (list && list.length > 0 && !selectedPeriod.value) {
    selectedPeriod.value = list[0]!.id
  }
})

// Insight is generated by a seed/heuristic pass, not automatically for every period — a
// period with no AI insight row yet is expected (not an error), so a 404 here resolves to
// null instead of failing the whole Promise.all below and hiding the other panels that did
// load successfully.
async function loadInsight(period?: string) {
  try {
    return await dashboardApi.insight(period)
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) return null
    throw err
  }
}

async function loadDashboard() {
  const period = selectedPeriod.value || undefined
  const [kpis, heatmap, departmentSummary, wordCloud, insight, alerts, extraQuestions] = await Promise.all([
    dashboardApi.hrKpis(period),
    dashboardApi.heatmap(period),
    dashboardApi.departmentSummary(period).catch(() => null),
    dashboardApi.wordCloud(period).catch(() => null),
    loadInsight(period),
    dashboardApi.alerts(period).catch(() => null),
    dashboardApi.extraQuestions(period),
  ])
  return { kpis, heatmap, departmentSummary, wordCloud, insight, alerts, extraQuestions }
}

const { data, loading, error, reload } = useAsyncData(loadDashboard)

watch(selectedPeriod, () => {
  if (selectedPeriod.value) reload()
})

const departmentOptions = computed(() => [
  { value: 'all', label: t('common.all') },
  ...(data.value?.heatmap.rows.map((r) => ({
    value: r.department.id,
    label: r.department.id === '__unassigned__' ? t('heatmap.unassigned') : r.department.name,
  })) ?? []),
])

const isFiltered = computed(() => selectedDepartment.value !== 'all')
const heatmapRows = computed(() =>
  selectedDepartment.value === 'all'
    ? (data.value?.heatmap.rows ?? [])
    : (data.value?.heatmap.rows.filter((row) => row.department.id === selectedDepartment.value) ?? []),
)
const departmentSummaryRows = computed(() => {
  const rows = data.value?.departmentSummary?.rows ?? []
  return selectedDepartment.value === 'all'
    ? rows
    : rows.filter((row) => row.departmentId === selectedDepartment.value)
})

watch(() => data.value?.heatmap.rows, (rows) => {
  if (rows && selectedDepartment.value !== 'all' && !rows.some((row) => row.department.id === selectedDepartment.value)) {
    selectedDepartment.value = 'all'
  }
})

const trendPoints = computed(() =>
  (data.value?.kpis.trend ?? []).map((p) => ({ label: p.month.slice(5), a: p.enps, b: p.satisfaction })),
)

function goToTopic(topicId: string, department: dashboardApi.HeatmapRow['department']) {
  router.push({
    path: `/dashboard/topics/${topicId}`,
    query: { department: department.id, period: selectedPeriod.value || undefined },
  })
}

</script>

<template>
  <HrLayout :breadcrumb="t('nav.dashboard')">
    <div class="toolbar">
      <div class="filters">
        <DropdownSelect v-model="selectedPeriod" :options="periodOptions" />
        <DropdownSelect v-model="selectedDepartment" :options="departmentOptions" />
      </div>
      <div class="actions">
        <Button variant="secondary">
          <Download :size="16" aria-hidden="true" />
          {{ t('common.export') }}
        </Button>
        <Button variant="secondary">
          <Mail :size="16" aria-hidden="true" />
          {{ t('common.sendEmail') }}
        </Button>
      </div>
    </div>

    <PrivacyBanner v-if="isFiltered" variant="filters-active" />

    <p v-if="loading">{{ t('common.loading') }}</p>
    <Alert v-else-if="error" variant="destructive">
      <AlertDescription>
        {{ t('common.loadError') }}
        <Button variant="link" size="sm" @click="reload">{{ t('common.retry') }}</Button>
      </AlertDescription>
    </Alert>

    <template v-else-if="data">
      <div class="kpi-row">
        <KpiCard
          :label="t('kpi.enps')"
          :value="String(data.kpis.enps.value)"
          :sublabel="`+${data.kpis.enps.deltaVsLastMonth} vs last month`"
          trend="up"
        />
        <KpiCard
          :label="t('kpi.satisfaction')"
          :value="`${data.kpis.satisfaction.value}/5`"
          :trend="data.kpis.satisfaction.trend"
        />
        <KpiCard
          :label="t('kpi.burnoutRisk')"
          :value="`${data.kpis.burnoutRisk.percentage}%`"
          :sublabel="`${data.kpis.burnoutRisk.departmentsAtRisk} ${t('kpi.departmentsToWatch')}`"
        />
        <KpiCard
          :label="t('kpi.responseRate')"
          :value="`${data.kpis.responseRate.percentage}%`"
          :sublabel="`${data.kpis.responseRate.responded}/${data.kpis.responseRate.total}`"
        />
      </div>

      <section class="panel">
        <h2>eNPS · {{ t('kpi.satisfaction') }}</h2>
        <TrendLineChart :points="trendPoints" series-a-label="eNPS" :series-b-label="t('kpi.satisfaction')" />
      </section>

      <div v-if="data.insight" class="two-col">
        <AiInsightPanel :insight="data.insight.insight" />
        <UrgentIssuesList :issues="data.insight.urgentIssues" />
      </div>
      <Alert v-else>
        <AlertDescription>{{ t('insight.notGenerated') }}</AlertDescription>
      </Alert>

      <section class="panel">
        <DashboardAlerts :alerts="data.alerts" :departments="data.heatmap.rows.map((row) => row.department)" />
      </section>

      <section class="panel">
        <h2>{{ t('heatmap.title') }}</h2>
        <p class="heatmap-scope">{{ t('heatmap.filterScope') }}</p>
        <HeatmapGrid :topics="data.heatmap.topics" :rows="heatmapRows" @cell-click="goToTopic" />
      </section>

      <div class="dashboard-lower-grid">
        <section class="panel department-summary-panel">
          <h2>{{ t('departmentScores.title') }}</h2>
          <DepartmentSummaryTable v-if="data.departmentSummary" :rows="departmentSummaryRows" />
          <p v-else class="wordcloud-error">{{ t('common.loadError') }}</p>
          <p class="summary-note">{{ t('departmentScores.headcountNote') }}</p>
          <p class="summary-note">{{ t('departmentScores.methodNote') }}</p>
        </section>

        <section class="panel wordcloud-panel">
          <h2>{{ t('kpi.sentimentDistribution') }}</h2>
          <SentimentBar :sentiment="data.kpis.sentiment" />
          <hr class="rule" />
          <h2>{{ t('wordcloud.title') }}</h2>
          <WordCloud v-if="data.wordCloud" :terms="data.wordCloud" compact />
          <p v-else class="wordcloud-error">{{ t('wordcloud.loadError') }}</p>
        </section>
      </div>

      <section v-if="data.extraQuestions.length > 0" class="panel">
        <h2>{{ t('periods.extraQuestions.resultsTitle') }}</h2>
        <ul class="extra-question-results">
          <li v-for="q in data.extraQuestions" :key="q.key">
            <span class="eq-label">{{ locale === 'th' ? q.label.th : q.label.en }}</span>
            <span class="eq-value">
              {{ q.average }}{{ q.type === 'enps_0_10' ? '/10' : '/5' }}
              <span class="eq-count">({{ q.respondentCount }} {{ t('drilldown.respondents') }})</span>
            </span>
          </li>
        </ul>
      </section>
    </template>
  </HrLayout>
</template>

<style scoped>
.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: var(--space-3);
}

.filters,
.actions {
  display: flex;
  gap: var(--space-2);
}

.kpi-row {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--space-3);
}

.kpi-card {
  padding: var(--space-4);
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.panel h2 {
  margin: 0 0 var(--space-4);
  font-size: var(--font-size-md);
  font-weight: 600;
  letter-spacing: -0.01em;
}

.heatmap-scope {
  margin: 0 0 var(--space-3);
  color: var(--color-text-muted);
  font-size: var(--font-size-xs);
}

.wordcloud-error {
  color: var(--color-text-muted);
  font-size: var(--font-size-sm);
}

.dashboard-lower-grid {
  display: grid;
  grid-template-columns: minmax(0, 3fr) minmax(220px, 1fr);
  gap: var(--space-4);
  align-items: start;
}

.department-summary-panel { min-width: 0; }
.wordcloud-panel { min-width: 0; }
.wordcloud-panel .rule { margin: var(--space-5) 0; }
.summary-note { margin: var(--space-3) 0 0; color: var(--color-text-muted); font-size: var(--font-size-xs); }

.two-col {
  display: grid;
  grid-template-columns: 2fr 1fr;
  gap: var(--space-4);
}

.extra-question-results {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.extra-question-results li {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
  font-size: var(--font-size-sm);
  padding: var(--space-2) 0;
  border-bottom: 1px solid var(--color-border);
}

.extra-question-results li:last-child {
  border-bottom: none;
}

.eq-label {
  font-weight: 600;
}

.eq-value {
  font-weight: 700;
  color: var(--color-accent-700);
}

.eq-count {
  font-weight: 400;
  color: var(--color-text-subtle);
  font-size: var(--font-size-xs);
}

@media (max-width: 1200px) {
  .kpi-row {
    grid-template-columns: repeat(3, 1fr);
  }
  .dashboard-lower-grid { grid-template-columns: 1fr; }
  .wordcloud-panel { max-width: 460px; }
}

@media (max-width: 900px) {
  .kpi-row {
    grid-template-columns: repeat(2, 1fr);
  }
  .two-col {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 560px) {
  .kpi-row {
    grid-template-columns: 1fr;
  }
  .toolbar {
    align-items: stretch;
  }
  .filters,
  .actions {
    flex-wrap: wrap;
  }
}
</style>
